# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 地形地势.py
# Created on: 2017-09-26 10:02:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 地形地势 <DEM>
# Description:
# 根据高程数据进行运算，地形地势分值越高，说明空间开发适宜程度越高； 地形地势 = 0，说明空间不适宜开发。
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")
arcpy.CheckOutExtension("3D")

# Script arguments
DEM = arcpy.GetParameterAsText(0)

# Local variables:
dem_cfl = DEM
dem_xc = dem_cfl
dem_dxds = dem_xc
dem_dxds_area = dem_dxds
dem_dxds_area_Layer = dem_dxds_area
dem_dxds_area_Layer__2_ = dem_dxds_area_Layer
dem_dxds_area_eli = dem_dxds_area_Layer__2_
dem_dxds_area_eli_Layer = dem_dxds_area_eli
dem_dxds_area_Layer__4_ = dem_dxds_area_eli_Layer
dem_dxds_pjjg = dem_dxds_area_Layer__4_
dem_pd = DEM
dem_pd_cfl = dem_pd

# Process: 重分类
arcpy.gp.Reclassify_sa(DEM, "", "408 1900 1;1900 2888 0", dem_cfl, "DATA")

# Process: 坡度
arcpy.Slope_3d(DEM, dem_pd, "DEGREE", "1")

# Process: 重分类 (2)
arcpy.gp.Reclassify_sa(dem_pd, "Value", "0 5.7000000000000002 4;5.7000000000000002 8.5 3;8.5 11.300000000000001 2;11.300000000000001 14 1;14 78 0", dem_pd_cfl, "DATA")

# Process: 乘
arcpy.gp.Times_sa(dem_cfl, dem_pd_cfl, dem_xc)

# Process: 栅格转面
arcpy.RasterToPolygon_conversion(dem_xc, dem_dxds, "SIMPLIFY", "VALUE")

# Process: 计算面积
arcpy.CalculateAreas_stats(dem_dxds, dem_dxds_area)

# Process: 创建要素图层
arcpy.MakeFeatureLayer_management(dem_dxds_area, dem_dxds_area_Layer, "\"GRIDCODE\" =  0 OR \"GRIDCODE\" =  1 OR \"GRIDCODE\" =  2 OR \"GRIDCODE\" =  3 OR \"GRIDCODE\" =  4", "", "Shape Shape VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE;F_AREA F_AREA VISIBLE NONE")

# Process: 按属性选择图层
arcpy.SelectLayerByAttribute_management(dem_dxds_area_Layer, "NEW_SELECTION", "F_AREA <10000")

# Process: 消除
arcpy.Eliminate_management(dem_dxds_area_Layer__2_, dem_dxds_area_eli, "AREA", "", "")

# Process: 创建要素图层 (2)
arcpy.MakeFeatureLayer_management(dem_dxds_area_eli, dem_dxds_area_eli_Layer, "\"GRIDCODE\" =  0 OR \"GRIDCODE\" =  1 OR \"GRIDCODE\" =  2 OR \"GRIDCODE\" =  3 OR \"GRIDCODE\" =  4", "", "Shape Shape VISIBLE NONE;OBJECTID OBJECTID VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE;ID ID VISIBLE NONE;GRIDCODE GRIDCODE VISIBLE NONE;Shape_Length_1 Shape_Length_1 VISIBLE NONE;Shape_Area_1 Shape_Area_1 VISIBLE NONE;F_AREA F_AREA VISIBLE NONE;Shape_length Shape_length VISIBLE NONE;Shape_area Shape_area VISIBLE NONE")

# Process: 按属性选择图层 (2)
arcpy.SelectLayerByAttribute_management(dem_dxds_area_eli_Layer, "NEW_SELECTION", "F_AREA <10000")

# Process: 消除 (2)
arcpy.Eliminate_management(dem_dxds_area_Layer__4_, dem_dxds_pjjg, "AREA", "", "")